services:
  mongo:
    image: mongo:7
    ports:
      - "${MONGO_PORT:-27019}:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=app

volumes:
  mongo-data: